# Makefile for nlibc minimal stubs
CC = gcc
CFLAGS = -Wall -Wextra -c -fPIC
LDFLAGS = -shared

all: libnlibc_stubs.a

nlibc_minimal_stubs.o: nlibc_minimal_stubs.c
	$(CC) $(CFLAGS) -o $@ $<

libnlibc_stubs.a: nlibc_minimal_stubs.o
	ar rcs $@ $^

install: libnlibc_stubs.a
	mkdir -p ../../../build/lib
	cp libnlibc_stubs.a ../../../build/lib/

clean:
	rm -f *.o *.a

.PHONY: all clean install
